import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { CatalogProvider } from "./context/catalogContext";
import { CartProvider } from "./context/cartContext";
import AudioChat from './components/audiochat';
import { LanguageProvider } from "./context/languageContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Voice Activated Kiosk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <CatalogProvider>
            <CartProvider>
              <AudioChat />
              {children}
            </CartProvider>
          </CatalogProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
